- name: restart vaultwarden
  become: True
  service:
    name: vaultwarden
    enabled: yes
    state: restarted

- name: restart nginx
  become: True
  service:
    name: nginx
    enabled: yes
    state: restarted